/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardScenarioRouteImport } from './routes/dashboard.scenario'
import { Route as DashboardQuickCreateRouteImport } from './routes/dashboard.quick-create'
import { Route as DashboardPipelinesRouteImport } from './routes/dashboard.pipelines'
import { Route as DashboardOverheadsRouteImport } from './routes/dashboard.overheads'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScenarioRoute = DashboardScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuickCreateRoute = DashboardQuickCreateRouteImport.update({
  id: '/quick-create',
  path: '/quick-create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelinesRoute = DashboardPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverheadsRoute = DashboardOverheadsRouteImport.update({
  id: '/overheads',
  path: '/overheads',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overheads': typeof DashboardOverheadsRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quick-create': typeof DashboardQuickCreateRoute
  '/dashboard/scenario': typeof DashboardScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overheads': typeof DashboardOverheadsRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quick-create': typeof DashboardQuickCreateRoute
  '/dashboard/scenario': typeof DashboardScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overheads': typeof DashboardOverheadsRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quick-create': typeof DashboardQuickCreateRoute
  '/dashboard/scenario': typeof DashboardScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/overheads'
    | '/dashboard/pipelines'
    | '/dashboard/quick-create'
    | '/dashboard/scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/overheads'
    | '/dashboard/pipelines'
    | '/dashboard/quick-create'
    | '/dashboard/scenario'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/overheads'
    | '/dashboard/pipelines'
    | '/dashboard/quick-create'
    | '/dashboard/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scenario': {
      id: '/dashboard/scenario'
      path: '/scenario'
      fullPath: '/dashboard/scenario'
      preLoaderRoute: typeof DashboardScenarioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quick-create': {
      id: '/dashboard/quick-create'
      path: '/quick-create'
      fullPath: '/dashboard/quick-create'
      preLoaderRoute: typeof DashboardQuickCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pipelines': {
      id: '/dashboard/pipelines'
      path: '/pipelines'
      fullPath: '/dashboard/pipelines'
      preLoaderRoute: typeof DashboardPipelinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overheads': {
      id: '/dashboard/overheads'
      path: '/overheads'
      fullPath: '/dashboard/overheads'
      preLoaderRoute: typeof DashboardOverheadsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardOverheadsRoute: typeof DashboardOverheadsRoute
  DashboardPipelinesRoute: typeof DashboardPipelinesRoute
  DashboardQuickCreateRoute: typeof DashboardQuickCreateRoute
  DashboardScenarioRoute: typeof DashboardScenarioRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOverheadsRoute: DashboardOverheadsRoute,
  DashboardPipelinesRoute: DashboardPipelinesRoute,
  DashboardQuickCreateRoute: DashboardQuickCreateRoute,
  DashboardScenarioRoute: DashboardScenarioRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
